<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <version>0.1</version>
    <packaging>jar</packaging>
    <groupId>com.nexus_auth_studios.deepLearning</groupId>
    <artifactId>AI_UsingJava</artifactId>
    <modelVersion>4.0.0</modelVersion>
    <repositories>
        <repository>
            <id>project-local-repo</id>
            <name></name>
            <url>file:///Volumes/ANUPS_SSD/water/JarDependencies</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
            <version>0.36.0</version>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>basicdataset</artifactId>
            <version>0.36.0</version>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-engine</artifactId>
            <version>0.36.0</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-native-cpu</artifactId>
            <version>2.7.1</version>
            <classifier>osx-aarch64</classifier>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>ai.djl.huggingface</groupId>
            <artifactId>tokenizers</artifactId>
            <version>0.36.0</version>
        </dependency>
    </dependencies>
</project>